"""File Generated by Sideko (sideko.dev)"""

from __future__ import annotations
import io
import typing
import pydantic
import typing_extensions

HttpxFile = typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]


class PostAccountEuroOfframpBody(typing_extensions.TypedDict):
    """
    No description specified
    """

    account_owner_name: typing_extensions.Required[str]
    account_owner_type: typing_extensions.Required[
        typing_extensions.Literal["individual", "business"]
    ]
    bank_name: typing_extensions.Required[str]
    business_identifier_code: typing_extensions.Required[str]
    business_name: typing_extensions.NotRequired[str]
    currency: typing_extensions.Required[typing_extensions.Literal["eur"]]
    first_name: typing_extensions.NotRequired[str]
    iban_account_number: typing_extensions.Required[str]
    iban_country_code: typing_extensions.Required[str]
    last_name: typing_extensions.NotRequired[str]


class _SerializerPostAccountEuroOfframpBody(pydantic.BaseModel):
    """
    Serializer for PostAccountEuroOfframpBody handling case conversions
    and file omitions as dictated by the API
    """

    model_config = pydantic.ConfigDict(
        populate_by_name=True,
    )

    account_owner_name: str = pydantic.Field(alias="accountOwnerName")
    account_owner_type: typing_extensions.Literal["individual", "business"] = (
        pydantic.Field(alias="accountOwnerType")
    )
    bank_name: str = pydantic.Field(alias="bankName")
    business_identifier_code: str = pydantic.Field(alias="businessIdentifierCode")
    business_name: typing.Optional[str] = pydantic.Field(
        alias="businessName", default=None
    )
    currency: typing_extensions.Literal["eur"] = pydantic.Field(alias="currency")
    first_name: typing.Optional[str] = pydantic.Field(alias="firstName", default=None)
    iban_account_number: str = pydantic.Field(alias="ibanAccountNumber")
    iban_country_code: str = pydantic.Field(alias="ibanCountryCode")
    last_name: typing.Optional[str] = pydantic.Field(alias="lastName", default=None)
