"""File Generated by Sideko (sideko.dev)"""

import io
import typing


import pydantic

ModelFiles = typing.List[
    typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]
]


class PostAccountUsdOnrampPlaidResponse(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    id: typing.Optional[str] = pydantic.Field(alias="id", default=None)
    invalid_fields: typing.Optional[typing.Any] = pydantic.Field(
        alias="invalidFields", default=None
    )
    message: typing.Optional[str] = pydantic.Field(alias="message", default=None)
    status: typing.Optional[str] = pydantic.Field(alias="status", default=None)
