"""File Generated by Sideko (sideko.dev)"""

from __future__ import annotations
import io
import typing
import pydantic
import typing_extensions

HttpxFile = typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]


class PostAccountUsdOnrampPlaidBody(typing_extensions.TypedDict):
    """
    No description specified
    """

    account_type: typing_extensions.Required[
        typing_extensions.Literal["CHECKING", "SAVING", "BUSINESS"]
    ]
    bank_name: typing_extensions.Required[str]
    plaid_processor_token: typing_extensions.Required[str]


class _SerializerPostAccountUsdOnrampPlaidBody(pydantic.BaseModel):
    """
    Serializer for PostAccountUsdOnrampPlaidBody handling case conversions
    and file omitions as dictated by the API
    """

    model_config = pydantic.ConfigDict(
        populate_by_name=True,
    )

    account_type: typing_extensions.Literal["CHECKING", "SAVING", "BUSINESS"] = (
        pydantic.Field(alias="accountType")
    )
    bank_name: str = pydantic.Field(alias="bankName")
    plaid_processor_token: str = pydantic.Field(alias="plaidProcessorToken")
