"""File Generated by Sideko (sideko.dev)"""

from v1_production.core import (
    default_request_options,
    SyncBaseClient,
    to_encodable,
    AsyncBaseClient,
    RequestOptions,
)
from v1_production.types.account.brl.offramp import params, models
import typing


class OfframpClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)

    # register sync api methods (keep comment for code generation)
    def create(
        self,
        *,
        data: typing.Optional[params.PostAccountBrlOfframpBody] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PostAccountBrlOfframpResponse:
        """
        no description available
        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(
            item=data, dump_with=params._SerializerPostAccountBrlOfframpBody
        )
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="POST",
            path="/account/brl/offramp",
            auth_names=["sec0"],
            json=_json,
            cast_to=models.PostAccountBrlOfframpResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncOfframpClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)

    # register async api methods (keep comment for code generation)
    async def create(
        self,
        *,
        data: typing.Optional[params.PostAccountBrlOfframpBody] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PostAccountBrlOfframpResponse:
        """
        no description available
        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(
            item=data, dump_with=params._SerializerPostAccountBrlOfframpBody
        )
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="POST",
            path="/account/brl/offramp",
            auth_names=["sec0"],
            json=_json,
            cast_to=models.PostAccountBrlOfframpResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
