"""File Generated by Sideko (sideko.dev)"""

import io
import typing


import pydantic

ModelFiles = typing.List[
    typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]
]


class GetTransferFiatToCryptoResponseTransferDetailsDestinationUser(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    business_name: typing.Optional[typing.Any] = pydantic.Field(
        alias="business_name", default=None
    )
    compliance_email: typing.Optional[str] = pydantic.Field(
        alias="compliance_email", default=None
    )
    legal_first_name: typing.Optional[str] = pydantic.Field(
        alias="legal_first_name", default=None
    )
    legal_last_name: typing.Optional[str] = pydantic.Field(
        alias="legal_last_name", default=None
    )


class GetTransferFiatToCryptoResponseTransferDetailsSourceAccount(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    account_number: typing.Optional[str] = pydantic.Field(
        alias="account_number", default=None
    )
    bank_name: typing.Optional[str] = pydantic.Field(alias="bank_name", default=None)
    id: typing.Optional[str] = pydantic.Field(alias="id", default=None)
    routing_number: typing.Optional[str] = pydantic.Field(
        alias="routing_number", default=None
    )


class GetTransferFiatToCryptoResponseTransferDetailsSourceUser(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    business_name: typing.Optional[typing.Any] = pydantic.Field(
        alias="business_name", default=None
    )
    compliance_email: typing.Optional[str] = pydantic.Field(
        alias="compliance_email", default=None
    )
    legal_first_name: typing.Optional[str] = pydantic.Field(
        alias="legal_first_name", default=None
    )
    legal_last_name: typing.Optional[str] = pydantic.Field(
        alias="legal_last_name", default=None
    )


class PostTransferFiatToCryptoResponseTransferDetails(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    amount: typing.Optional[int] = pydantic.Field(alias="amount", default=None)
    chain: typing.Optional[str] = pydantic.Field(alias="chain", default=None)
    created_at: typing.Optional[str] = pydantic.Field(alias="createdAt", default=None)
    destination_currency: typing.Optional[str] = pydantic.Field(
        alias="destinationCurrency", default=None
    )
    destination_user_id: typing.Optional[str] = pydantic.Field(
        alias="destinationUserId", default=None
    )
    id: typing.Optional[str] = pydantic.Field(alias="id", default=None)
    is_instant: typing.Optional[bool] = pydantic.Field(alias="isInstant", default=None)
    request_id: typing.Optional[str] = pydantic.Field(alias="requestId", default=None)
    source_account_id: typing.Optional[str] = pydantic.Field(
        alias="sourceAccountId", default=None
    )
    source_currency: typing.Optional[str] = pydantic.Field(
        alias="sourceCurrency", default=None
    )
    source_user_id: typing.Optional[str] = pydantic.Field(
        alias="sourceUserId", default=None
    )
    status: typing.Optional[str] = pydantic.Field(alias="status", default=None)


class GetTransferFiatToCryptoResponseTransferDetails(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    amount: typing.Optional[str] = pydantic.Field(alias="amount", default=None)
    chain: typing.Optional[str] = pydantic.Field(alias="chain", default=None)
    created_at: typing.Optional[str] = pydantic.Field(alias="createdAt", default=None)
    destination_currency: typing.Optional[str] = pydantic.Field(
        alias="destinationCurrency", default=None
    )
    destination_user: typing.Optional[
        GetTransferFiatToCryptoResponseTransferDetailsDestinationUser
    ] = pydantic.Field(alias="destinationUser", default=None)
    destination_user_id: typing.Optional[str] = pydantic.Field(
        alias="destinationUserId", default=None
    )
    id: typing.Optional[str] = pydantic.Field(alias="id", default=None)
    request_id: typing.Optional[str] = pydantic.Field(alias="requestId", default=None)
    source_account: typing.Optional[
        GetTransferFiatToCryptoResponseTransferDetailsSourceAccount
    ] = pydantic.Field(alias="sourceAccount", default=None)
    source_account_id: typing.Optional[str] = pydantic.Field(
        alias="sourceAccountId", default=None
    )
    source_currency: typing.Optional[str] = pydantic.Field(
        alias="sourceCurrency", default=None
    )
    source_user: typing.Optional[
        GetTransferFiatToCryptoResponseTransferDetailsSourceUser
    ] = pydantic.Field(alias="sourceUser", default=None)
    source_user_id: typing.Optional[str] = pydantic.Field(
        alias="sourceUserId", default=None
    )
    status: typing.Optional[str] = pydantic.Field(alias="status", default=None)
    transaction_hash: typing.Optional[typing.Any] = pydantic.Field(
        alias="transactionHash", default=None
    )
    updated_at: typing.Optional[str] = pydantic.Field(alias="updatedAt", default=None)


class PostTransferFiatToCryptoResponse(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    transfer_details: typing.Optional[
        PostTransferFiatToCryptoResponseTransferDetails
    ] = pydantic.Field(alias="transferDetails", default=None)
    transfer_type: typing.Optional[str] = pydantic.Field(
        alias="transferType", default=None
    )


class GetTransferFiatToCryptoResponse(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    transfer_details: typing.Optional[
        GetTransferFiatToCryptoResponseTransferDetails
    ] = pydantic.Field(alias="transferDetails", default=None)
    transfer_type: typing.Optional[str] = pydantic.Field(
        alias="transferType", default=None
    )
