"""File Generated by Sideko (sideko.dev)"""

import io
import typing


import pydantic

ModelFiles = typing.List[
    typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]
]


class GetTransferConversionRateCryptoToFiatResponse(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    conversion_rate: typing.Optional[str] = pydantic.Field(
        alias="conversionRate", default=None
    )
    from_currency: typing.Optional[str] = pydantic.Field(
        alias="fromCurrency", default=None
    )
    to_currency: typing.Optional[str] = pydantic.Field(alias="toCurrency", default=None)
    vaild_from: typing.Optional[str] = pydantic.Field(alias="vaildFrom", default=None)
    vaild_until: typing.Optional[str] = pydantic.Field(alias="vaildUntil", default=None)
