"""File Generated by Sideko (sideko.dev)"""

import io
import typing


import pydantic

ModelFiles = typing.List[
    typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]
]


class PostAccountBrlReceiverResponse(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    country: typing.Optional[str] = pydantic.Field(alias="country", default=None)
    email_field: typing.Optional[str] = pydantic.Field(alias="email", default=None)
    id: typing.Optional[str] = pydantic.Field(alias="id", default=None)
    type: typing.Optional[str] = pydantic.Field(alias="type", default=None)
