"""File Generated by Sideko (sideko.dev)"""

from v1_production.core import (
    AsyncBaseClient,
    default_request_options,
    to_encodable,
    SyncBaseClient,
    QueryParams,
    RequestOptions,
    encode_param,
)
from v1_production.resources.transfer.crypto_to_fiat.all import (
    AllClient,
    AsyncAllClient,
)
import typing
from v1_production.types.transfer.crypto_to_fiat import models, params


class CryptoToFiatClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.all = AllClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)
    def create(
        self,
        *,
        data: typing.Optional[params.PostTransferCryptoToFiatBody] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PostTransferCryptoToFiatResponse:
        """
        Liquidate stablecoin into fiat currency and send to a destination bank account
        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(
            item=data, dump_with=params._SerializerPostTransferCryptoToFiatBody
        )
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="POST",
            path="/transfer/crypto-to-fiat",
            auth_names=["sec0"],
            json=_json,
            cast_to=models.PostTransferCryptoToFiatResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)

    def list(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> models.GetTransferCryptoToFiatResponse:
        """
        Get the transfer history of a specific stablecoin to fiat transfer
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        _query["id"] = encode_param(id, False)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="GET",
            path="/transfer/crypto-to-fiat",
            auth_names=["sec0"],
            query_params=_query,
            cast_to=models.GetTransferCryptoToFiatResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncCryptoToFiatClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.all = AsyncAllClient(base_client=self._base_client)

    # register async api methods (keep comment for code generation)
    async def create(
        self,
        *,
        data: typing.Optional[params.PostTransferCryptoToFiatBody] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PostTransferCryptoToFiatResponse:
        """
        Liquidate stablecoin into fiat currency and send to a destination bank account
        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(
            item=data, dump_with=params._SerializerPostTransferCryptoToFiatBody
        )
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="POST",
            path="/transfer/crypto-to-fiat",
            auth_names=["sec0"],
            json=_json,
            cast_to=models.PostTransferCryptoToFiatResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)

    async def list(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> models.GetTransferCryptoToFiatResponse:
        """
        Get the transfer history of a specific stablecoin to fiat transfer
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        _query["id"] = encode_param(id, False)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="GET",
            path="/transfer/crypto-to-fiat",
            auth_names=["sec0"],
            query_params=_query,
            cast_to=models.GetTransferCryptoToFiatResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
