"""File Generated by Sideko (sideko.dev)"""

from v1_production.core import SyncBaseClient, AsyncBaseClient
from v1_production.resources.account.on_ramp_rail.virtual_account import (
    AsyncVirtualAccountClient,
    VirtualAccountClient,
)


class OnRampRailClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.virtual_account = VirtualAccountClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)


class AsyncOnRampRailClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.virtual_account = AsyncVirtualAccountClient(base_client=self._base_client)

    # register async api methods (keep comment for code generation)
