"""File Generated by Sideko (sideko.dev)"""

import io
import typing


import pydantic

ModelFiles = typing.List[
    typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]
]


class PostTosLinkResponse(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    signed_agreement_id: typing.Optional[str] = pydantic.Field(
        alias="signedAgreementId", default=None
    )
    url: typing.Optional[str] = pydantic.Field(alias="url", default=None)
