"""File Generated by Sideko (sideko.dev)"""

from __future__ import annotations
import io
import typing
import pydantic
import typing_extensions

HttpxFile = typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]


class PostTosLinkBody(typing_extensions.TypedDict):
    """
    No description specified
    """

    idempotency_key: typing_extensions.Required[str]
    redirect_url: typing_extensions.NotRequired[str]
    template_id: typing_extensions.NotRequired[str]


class _SerializerPostTosLinkBody(pydantic.BaseModel):
    """
    Serializer for PostTosLinkBody handling case conversions
    and file omitions as dictated by the API
    """

    model_config = pydantic.ConfigDict(
        populate_by_name=True,
    )

    idempotency_key: str = pydantic.Field(alias="idempotencyKey")
    redirect_url: typing.Optional[str] = pydantic.Field(
        alias="redirectUrl", default=None
    )
    template_id: typing.Optional[str] = pydantic.Field(alias="templateId", default=None)
