"""File Generated by Sideko (sideko.dev)"""

from v1_production.core import (
    SyncBaseClient,
    default_request_options,
    AsyncBaseClient,
    RequestOptions,
    encode_param,
    QueryParams,
)
import typing
from v1_production.types.transfer.fiat_to_crypto.all import models


class AllClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)

    # register sync api methods (keep comment for code generation)
    def list(
        self,
        *,
        created_after: typing.Optional[str] = None,
        created_before: typing.Optional[str] = None,
        limit: typing.Optional[str] = None,
        user_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.GetTransferFiatToCryptoAllResponse:
        """
        Get all the transfer history of a user or your organization
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if created_after is not None:
            _query["createdAfter"] = encode_param(created_after, False)
        if created_before is not None:
            _query["createdBefore"] = encode_param(created_before, False)
        if limit is not None:
            _query["limit"] = encode_param(limit, False)
        if user_id is not None:
            _query["userId"] = encode_param(user_id, False)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="GET",
            path="/transfer/fiat-to-crypto/all",
            auth_names=["sec0"],
            query_params=_query,
            cast_to=models.GetTransferFiatToCryptoAllResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncAllClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)

    # register async api methods (keep comment for code generation)
    async def list(
        self,
        *,
        created_after: typing.Optional[str] = None,
        created_before: typing.Optional[str] = None,
        limit: typing.Optional[str] = None,
        user_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.GetTransferFiatToCryptoAllResponse:
        """
        Get all the transfer history of a user or your organization
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if created_after is not None:
            _query["createdAfter"] = encode_param(created_after, False)
        if created_before is not None:
            _query["createdBefore"] = encode_param(created_before, False)
        if limit is not None:
            _query["limit"] = encode_param(limit, False)
        if user_id is not None:
            _query["userId"] = encode_param(user_id, False)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="GET",
            path="/transfer/fiat-to-crypto/all",
            auth_names=["sec0"],
            query_params=_query,
            cast_to=models.GetTransferFiatToCryptoAllResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
