"""File Generated by Sideko (sideko.dev)"""

from __future__ import annotations
import io
import typing
import pydantic
import typing_extensions

HttpxFile = typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]


class PostAccountUsdOfframpBody(typing_extensions.TypedDict):
    """
    No description specified
    """

    account_number: typing_extensions.Required[str]
    account_owner_name: typing_extensions.Required[str]
    account_owner_type: typing_extensions.Required[
        typing_extensions.Literal["individual", "business"]
    ]
    bank_name: typing_extensions.Required[str]
    city: typing_extensions.Required[str]
    country: typing_extensions.Required[str]
    currency: typing_extensions.Required[typing_extensions.Literal["usd"]]
    postal_code: typing_extensions.Required[str]
    routing_number: typing_extensions.Required[str]
    state: typing_extensions.Required[str]
    street_line1: typing_extensions.Required[str]
    street_line2: typing_extensions.NotRequired[str]


class _SerializerPostAccountUsdOfframpBody(pydantic.BaseModel):
    """
    Serializer for PostAccountUsdOfframpBody handling case conversions
    and file omitions as dictated by the API
    """

    model_config = pydantic.ConfigDict(
        populate_by_name=True,
    )

    account_number: str = pydantic.Field(alias="accountNumber")
    account_owner_name: str = pydantic.Field(alias="accountOwnerName")
    account_owner_type: typing_extensions.Literal["individual", "business"] = (
        pydantic.Field(alias="accountOwnerType")
    )
    bank_name: str = pydantic.Field(alias="bankName")
    city: str = pydantic.Field(alias="city")
    country: str = pydantic.Field(alias="country")
    currency: typing_extensions.Literal["usd"] = pydantic.Field(alias="currency")
    postal_code: str = pydantic.Field(alias="postalCode")
    routing_number: str = pydantic.Field(alias="routingNumber")
    state: str = pydantic.Field(alias="state")
    street_line1: str = pydantic.Field(alias="streetLine1")
    street_line2: typing.Optional[str] = pydantic.Field(
        alias="streetLine2", default=None
    )
