"""File Generated by Sideko (sideko.dev)"""

from v1_production.core import (
    default_request_options,
    RequestOptions,
    to_encodable,
    SyncBaseClient,
    encode_param,
    AsyncBaseClient,
    QueryParams,
)
from v1_production.types.user_business import params, models
import typing


class UserBusinessClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)

    # register sync api methods (keep comment for code generation)
    def put(
        self,
        *,
        data: typing.Optional[params.PutUserBusinessBody] = None,
        user_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PutUserBusinessResponse:
        """
        Use this endpoint to update a User. Submit only the properties you wish to update. For example, if the actions array from the Create User response indicates the ID was blurry, you could use this endpoint to submit a new govIdFront.
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        _query["userId"] = encode_param(user_id, False)
        _json = to_encodable(item=data, dump_with=params._SerializerPutUserBusinessBody)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="PUT",
            path="/user#business",
            auth_names=["sec0"],
            query_params=_query,
            json=_json,
            cast_to=models.PutUserBusinessResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncUserBusinessClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)

    # register async api methods (keep comment for code generation)
    async def put(
        self,
        *,
        data: typing.Optional[params.PutUserBusinessBody] = None,
        user_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PutUserBusinessResponse:
        """
        Use this endpoint to update a User. Submit only the properties you wish to update. For example, if the actions array from the Create User response indicates the ID was blurry, you could use this endpoint to submit a new govIdFront.
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        _query["userId"] = encode_param(user_id, False)
        _json = to_encodable(item=data, dump_with=params._SerializerPutUserBusinessBody)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="PUT",
            path="/user#business",
            auth_names=["sec0"],
            query_params=_query,
            json=_json,
            cast_to=models.PutUserBusinessResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
