"""File Generated by Sideko (sideko.dev)"""

from v1_production.core import (
    SyncBaseClient,
    RequestOptions,
    to_encodable,
    AsyncBaseClient,
    default_request_options,
)
from v1_production.types.account.brl.receiver import models, params
import typing


class ReceiverClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)

    # register sync api methods (keep comment for code generation)
    def create(
        self,
        *,
        data: typing.Optional[params.PostAccountBrlReceiverBody] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PostAccountBrlReceiverResponse:
        """
        no description available
        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(
            item=data, dump_with=params._SerializerPostAccountBrlReceiverBody
        )
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="POST",
            path="/account/brl/receiver",
            auth_names=["sec0"],
            json=_json,
            cast_to=models.PostAccountBrlReceiverResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncReceiverClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)

    # register async api methods (keep comment for code generation)
    async def create(
        self,
        *,
        data: typing.Optional[params.PostAccountBrlReceiverBody] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PostAccountBrlReceiverResponse:
        """
        no description available
        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(
            item=data, dump_with=params._SerializerPostAccountBrlReceiverBody
        )
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="POST",
            path="/account/brl/receiver",
            auth_names=["sec0"],
            json=_json,
            cast_to=models.PostAccountBrlReceiverResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
