"""File Generated by Sideko (sideko.dev)"""

import io
import typing


import pydantic

ModelFiles = typing.List[
    typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]
]


class PostAccountBrlOfframpResponse(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    bank_country: typing.Optional[str] = pydantic.Field(
        alias="bankCountry", default=None
    )
    currency: typing.Optional[str] = pydantic.Field(alias="currency", default=None)
    id: typing.Optional[str] = pydantic.Field(alias="id", default=None)
    name: typing.Optional[str] = pydantic.Field(alias="name", default=None)
    pix_key: typing.Optional[str] = pydantic.Field(alias="pixKey", default=None)
    receiver_id: typing.Optional[str] = pydantic.Field(alias="receiverId", default=None)
