"""File Generated by Sideko (sideko.dev)"""

from v1_production.core import AsyncBaseClient, SyncBaseClient
from v1_production.resources.transfer.conversion_rate.crypto_to_fiat import (
    CryptoToFiatClient,
    AsyncCryptoToFiatClient,
)


class ConversionRateClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.crypto_to_fiat = CryptoToFiatClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)


class AsyncConversionRateClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.crypto_to_fiat = AsyncCryptoToFiatClient(base_client=self._base_client)

    # register async api methods (keep comment for code generation)
