"""File Generated by Sideko (sideko.dev)"""

from v1_production.core import (
    AsyncBaseClient,
    SyncBaseClient,
    default_request_options,
    to_encodable,
    RequestOptions,
)
from v1_production.types.tos_link import models, params
import typing


class TosLinkClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)

    # register sync api methods (keep comment for code generation)
    def create(
        self,
        *,
        data: typing.Optional[params.PostTosLinkBody] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PostTosLinkResponse:
        """
        The Terms of Service page must be displayed to the end user. This page can be whitelabeled upon request.
        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(item=data, dump_with=params._SerializerPostTosLinkBody)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="POST",
            path="/tos-link",
            auth_names=["sec0"],
            json=_json,
            cast_to=models.PostTosLinkResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncTosLinkClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)

    # register async api methods (keep comment for code generation)
    async def create(
        self,
        *,
        data: typing.Optional[params.PostTosLinkBody] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PostTosLinkResponse:
        """
        The Terms of Service page must be displayed to the end user. This page can be whitelabeled upon request.
        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(item=data, dump_with=params._SerializerPostTosLinkBody)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="POST",
            path="/tos-link",
            auth_names=["sec0"],
            json=_json,
            cast_to=models.PostTosLinkResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
